language: minimal

dist: focal

install:
  - IMAGE_SYNCER_URL="https://github.com/AliyunContainerService/image-syncer/releases/download/v1.2.0/image-syncer-v1.2.0-linux-amd64.tar.gz" ;
  - wget -nv ${IMAGE_SYNCER_URL} -O tmp.tgz && tar -C ./ -xzf ./tmp.tgz && rm -f ./tmp.tgz ; 

before_script:
  - echo IP=$(curl -s http://ifconfig.me/ip)
  - sync_image_tags() { python ./prepare.py "$@" && ./image-syncer --proc 8 --config ./config.json ; }


jobs:
  include:
    - name: qpod/qpod
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/atom
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/base
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/core
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/py-data
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/py-nlp
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/py-cv
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/py-bio
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/py-chem
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/py-std
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/py-jdk
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/r-mini
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/r-std
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/r-latext
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/r-studio
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/node
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/jdk
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/julia
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/go
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/octave
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/cuda_10.0
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/cuda_10.1
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/cuda_10.2
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/cuda_11.0
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/py-cuda-10.0
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/py-cuda-10.1
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/py-cuda-10.2
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/full-cuda
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/tf1
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/tf2
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/torch
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/core-dev
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/full
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/cuda-dev
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: qpod/full-cuda
      script: sync_image_tags "${TRAVIS_JOB_NAME}"

notifications:
  slack: q-pod:lrzKf5Ff1Ao1MGclzElR23j4
