language: minimal

dist: focal

install:
  - IMAGE_SYNCER_URL="https://github.com/AliyunContainerService/image-syncer/releases/download/v1.1.0/image-syncer-v1.1.0-linux-amd64.tar.gz" ;
  - wget -nv ${IMAGE_SYNCER_URL} -O tmp.tgz && tar -C ./ -xzf ./tmp.tgz && rm -f ./tmp.tgz ; 

before_script:
  - echo IP=$(curl -s http://ifconfig.me/ip)
  - sync_image_tags() { python ./prepare.py "$@" && ./image-syncer --proc 8 --config ./config.json ; }


jobs:
  include:
    - name: base
      script:
        - sync_image_tags "${TRAVIS_JOB_NAME}"


    - name: "base-cuda_10.1"
      script:
        - sync_image_tags "${TRAVIS_JOB_NAME}"

    - name: "cuda"
      script:
        - sync_image_tags "${TRAVIS_JOB_NAME}"


    - name: "base-cuda_10.2"
      script:
        - sync_image_tags "${TRAVIS_JOB_NAME}"

    - name: "base-cuda_11.0"
      script:
        - sync_image_tags "${TRAVIS_JOB_NAME}"


    - name: "jupyter-mini"
      script:
        - sync_image_tags "${TRAVIS_JOB_NAME}"

    - name: "jupyter-mini-cuda"
      script:
        - sync_image_tags "${TRAVIS_JOB_NAME}"

    - name: "jupyter-std"
      script:
      - sync_image_tags "${TRAVIS_JOB_NAME}"

    - name: "jupyter-full"
      script:
        - sync_image_tags "${TRAVIS_JOB_NAME}"

    - name: "jupyter-full-cuda"
      script:
        - sync_image_tags "${TRAVIS_JOB_NAME}"


    - name: "r-mini"
      script:
        - sync_image_tags "${TRAVIS_JOB_NAME}"

    - name: "r-std"
      script:
        - sync_image_tags "${TRAVIS_JOB_NAME}"

    - name: "r-latex"
      script:
        - sync_image_tags "${TRAVIS_JOB_NAME}"

    - name: "r-studio"
      script:
        - sync_image_tags "${TRAVIS_JOB_NAME}"

    - name: "py-std"
      script:
        - sync_image_tags "${TRAVIS_JOB_NAME}"

    - name: "py-jdk"
      script:
        - sync_image_tags "${TRAVIS_JOB_NAME}"

    - name: "py-cuda"
      script:
        - sync_image_tags "${TRAVIS_JOB_NAME}"

    - name: "go"
      script:
        - sync_image_tags "${TRAVIS_JOB_NAME}"

    - name: "julia"
      script:
        - sync_image_tags "${TRAVIS_JOB_NAME}"

    - name: "octave"
      script:
        - sync_image_tags "${TRAVIS_JOB_NAME}"

    - name: "full"
      script:
        - sync_image_tags "${TRAVIS_JOB_NAME}"
      
    - name: "latest"
      script:
        - sync_image_tags "${TRAVIS_JOB_NAME}"

    - name: "full-cuda"
      script:
        - sync_image_tags "${TRAVIS_JOB_NAME}"
    
    - name: "latest-cuda"
      script:
        - sync_image_tags "${TRAVIS_JOB_NAME}"


notifications:
  slack: q-pod:lrzKf5Ff1Ao1MGclzElR23j4
