language: minimal

dist: focal

install:
  - IMAGE_SYNCER_URL="https://github.com/AliyunContainerService/image-syncer/releases/download/v1.2.0/image-syncer-v1.2.0-linux-amd64.tar.gz" ;
  - wget -nv ${IMAGE_SYNCER_URL} -O tmp.tgz && tar -C ./ -xzf ./tmp.tgz && rm -f ./tmp.tgz ; 

before_script:
  - echo IP=$(curl -s http://ifconfig.me/ip)
  - sync_image_tags() { python ./prepare.py "$@" && ./image-syncer --proc 8 --config ./config.json ; }


jobs:
  include:
    - name: qpod
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: atom
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: base
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: core
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: py-data
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: py-nlp
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: py-cv
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: py-bio
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: py-chem
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: py-std
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: py-jdk
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: r-mini
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: r-std
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: r-latext
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: r-studio
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: node
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: jdk
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: julia
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: go
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: octave
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: cuda_10.0
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: cuda_10.1
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: cuda_10.2
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: cuda_11.0
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: py-cuda-10.0
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: py-cuda-10.1
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: py-cuda-10.2
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: full-cuda
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: tf1
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: tf2
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: torch
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: core-dev
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: full
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: cuda-dev
      script: sync_image_tags "${TRAVIS_JOB_NAME}"
    - name: full-cuda
      script: sync_image_tags "${TRAVIS_JOB_NAME}"

notifications:
  slack: q-pod:lrzKf5Ff1Ao1MGclzElR23j4
