name: Build Docker Images

on:
  pull_request:
    paths-ignore:
      - "*.md"

  push:
    branches:
      - master
    paths-ignore:
      - "*.md"

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    if: >
      !contains(github.event.head_commit.message, 'ci skip') &&
      !contains(github.event.pull_request.title, 'ci skip')
    steps:
      - name: Clone Main Repo
        uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dev Dependencies
        run: python -m pip install --upgrade pip
      - name: Build Docker Images
        run: |
          ls -alh
          source ./docker-images/tool.sh
          build_image atom  latest  docker_atom/Dockerfile
          build_image base  latest  docker_base/Dockerfile
        env:
          # Full logs for CI build
          BUILDKIT_PROGRESS: plain
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master'
        run: >
          echo '${{secrets.DOCKERHUB_PASSWORD}}' | docker login --username
          '${{secrets.DOCKERHUB_USERNAME}}' --password-stdin
      - name: Push Images to DockerHub
        if: github.ref == 'refs/heads/master'
        run: docker images
