name: Build Docker Images

on:
  pull_request:
    paths-ignore:
      - "*.md"

  push:
    branches:
      - master
    paths-ignore:
      - "*.md"

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    if: >
      !contains(github.event.head_commit.message, 'ci skip') &&
      !contains(github.event.pull_request.title, 'ci skip')
    steps:
      - name: Clone Main Repo
        uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Setup Environment
        run: |
          echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json && sudo service docker restart && docker info
          python -m pip install --upgrade pip
      - name: Build Docker Images
        env:
          # Full logs for CI build
          BUILDKIT_PROGRESS: plain
        run: |
          source ./tool.sh
          build_image atom  latest  docker_atom/Dockerfile
          build_image base  latest  docker_base/Dockerfile
          build_image core  latest docker_core/Dockerfile        
            --build-arg "ARG_PROFILE_PYTHON=base,datascience,database,nlp,cv,bio,chem,tf2,torch"
            --build-arg "ARG_PROFILE_R=base,datascience,rstudio,rshiny"
            --build-arg "ARG_PROFILE_NODEJS=base"
            --build-arg "ARG_PROFILE_JAVA=base,maven"
            --build-arg "ARG_PROFILE_GO=base"
            --build-arg "ARG_PROFILE_JULIA=base"
            --build-arg "ARG_PROFILE_OCTAVE=base"
            --build-arg "ARG_PROFILE_LATEX=base,cjk"
          build_image py-data latest docker_core/Dockerfile --build-arg "ARG_PROFILE_PYTHON=datascience,database"
          build_image py-nlp  latest docker_core/Dockerfile --build-arg "ARG_PROFILE_PYTHON=datascience,nlp"
          build_image py-cv   latest docker_core/Dockerfile --build-arg "ARG_PROFILE_PYTHON=datascience,cv"
          build_image py-bio  latest docker_core/Dockerfile --build-arg "ARG_PROFILE_PYTHON=datascience,bio"
          build_image py-bio  latest docker_core/Dockerfile --build-arg "ARG_PROFILE_PYTHON=datascience,chem"
          build_image py-std  latest docker_core/Dockerfile --build-arg "ARG_PROFILE_PYTHON=datascience,database,nlp,cv,bio,chem"
          build_image py-jdk  latest docker_core/Dockerfile --build-arg "ARG_PROFILE_PYTHON=datascience,database,nlp,cv,bio,chem" --build-arg "ARG_PROFILE_JAVA=base"
          build_image r-mini  latest docker_core/Dockerfile --build-arg "ARG_PROFILE_R=base"
          build_image r-std   latest docker_core/Dockerfile --build-arg "ARG_PROFILE_R=base,datascience" --build-arg "ARG_PROFILE_JAVA=base"
          build_image r-latex latest docker_core/Dockerfile --build-arg "ARG_PROFILE_R=base,datascience" --build-arg "ARG_PROFILE_JAVA=base" --build-arg "ARG_PROFILE_LATEX=base,cjk"
          build_image r-studio  latest docker_core/Dockerfile --build-arg "ARG_PROFILE_R=base,datascience,rstudio,rshiny" --build-arg "ARG_PROFILE_JAVA=base" --build-arg "ARG_PROFILE_LATEX=base,cjk"
          build_image node    latest docker_core/Dockerfile --build-arg "ARG_PROFILE_NODEJS=base"
          build_image jdk     latest docker_core/Dockerfile --build-arg "ARG_PROFILE_JAVA=base"
          build_image julia   latest docker_core/Dockerfile --build-arg "ARG_PROFILE_JULIA=base"
          build_image go      latest docker_core/Dockerfile --build-arg "ARG_PROFILE_GO=base"
          docker images
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master'
        run: >
          echo '${{secrets.DOCKERHUB_PASSWORD}}' | docker login --username
          '${{secrets.DOCKERHUB_USERNAME}}' --password-stdin
      - name: Push Images to DockerHub
        if: github.ref == 'refs/heads/master'
        run: docker images
